### ISSUE TITLE
Running code sample from readme yields `error: expected define, or extern`

### ISSUE THREAD

**Issue by thenickcox** [Hacker-007/envious#33]
![image](https://user-images.githubusercontent.com/702327/121256879-e25c1300-c861-11eb-9c4c-5a15a1dfc433.png)

Expected:
Output to be `'Y'`

Observed:
`error: expected define, or extern`

**Comment by thenickcox** [comment]
Okay, that makes total sense. But now if I try to wrap it in a function like `main` and begin it with `define`, I get `expected prefix expression`. What's an example of a hello world that will compile and run here?

I tried

```rust
define main() :: Int = // I know this doesn't return an Int, but you said you didn't have void implemented, so  ¯\_(ツ)_/¯
  define add(x: Int, y: Int) :: Int = x + y
  print(add(2,3))
```

And got that it expected a prefix.

Maybe I just haven't had enough coffee.

**Comment by Hacker-007** [comment]
The first comment is that the types of the function do not add up. As a function, `print` is not defined yet that would not work. Next, the function `print` returns a `Void` type. So, the main function should return `Void` (I believe Void as a type is implemented). The actual error that you are referencing has to do with the parser. The parser looks to the right of the main function and realizes that there is a single expression. The body provided, however, is a define expression or a new function. This is currently not implemented because it requires closures to be implemented, which once again goes back to a GC.

The code sample below should work:

```
extern print(Int) :: Void // Define an external print function that takes an Int and returns nothing. This will have to be linked later.
define add(x: Int, y: Int) :: Int = x + y // Define the add function
define main() :: Void = print(add(2, 3)) // Create the main function that returns no value whose body is the result of calling the print function.
```

**Comment by thenickcox** [comment]
Yep! I can confirm that compiles now. So I'll be _extra_ excited when the TUI shows the output rather than the compiled code, which I know is non-trivial and I know you're working on.
